#!/usr/bin/env bash

export WKHTMLTOPDF_SERVER="${WKHTMLTOPDF_SERVER:-http://localhost:2777}"

HEADER_HTML=$(echo "$*" | grep -o -- '--header-html [^ ]*' | cut -d ' ' -f 2)
FOOTER_HTML=$(echo "$*" | grep -o -- '--footer-html [^ ]*' | cut -d ' ' -f 2)
OUTPUT_PDF=$(echo "$*" | awk '{print $NF}')
BODY_HTML=$(echo "$*" | awk '{print $(NF-1)}')
ARGS=$(echo "$*" | sed -e "s/--header-html $HEADER_HTML//g" | sed -e "s/--footer-html $FOOTER_HTML//g" | sed -e "s/$OUTPUT_PDF//g" | sed -e "s/$BODY_HTML//g" | sed -e "s/  / /g")

echo "HEADER_HTML: $HEADER_HTML"
echo "FOOTER_HTML: $FOOTER_HTML"
echo "BODY_HTML: $BODY_HTML"
echo "OUTPUT_PDF: $OUTPUT_PDF"

# Check if OUTPUT_PDF ends with .pdf
if [ "${OUTPUT_PDF: -4}" != ".pdf" ]; then
    echo "Output file must end with .pdf"
    exit 1
fi
    
curl -X POST \
    -F "args=$ARGS" \
    -F "header_html=@$HEADER_HTML" \
    -F "footer_html=@$FOOTER_HTML" \
    -F "body_html=@$BODY_HTML" \
    -o "$OUTPUT_PDF" \
    "$WKHTMLTOPDF_SERVER/generate"