#!/usr/bin/env bash

user_is_installing_package=false

if [ ! -z "$APT_INSTALL" ]; then
    echo "Installing packages: $APT_INSTALL"
    user_is_installing_package=true
    env DEBIAN_FRONTEND=noninteractive apt update
    env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends $APT_INSTALL
fi

if [ ! -z "$PIP_INSTALL" ]; then
    echo "Installing packages: $PIP_INSTALL"
    user_is_installing_package=true
    pip install $PIP_INSTALL
fi

if [ ! -z "$PIP_INSTALL_FILE" ]; then
    echo "Installing packages from file: $PIP_INSTALL_FILE"
    user_is_installing_package=true
    requirements-install $PIP_INSTALL_FILE
fi

if $user_is_installing_package; then
    echo "Note: package installation using APT_INSTALL, PIP_INSTALL, or PIP_INSTALL_FILE should only be used for development and testing purposes."
fi