#!/usr/bin/env bash

if [[ "${OUID}" -lt 1000 ]] || [[ "${OUID}" -gt 65534 ]]; then
    echo "OUID must be between 1000 and 65534" 2>&1
    exit 1
fi

if [[ "${OGID}" -lt 1000 ]] || [[ "${OGID}" -gt 65534 ]]; then
    echo "OGID must be between 1000 and 65534" 2>&1
    exit 1
fi

if [[ -z "$NO_CHOWN" ]]; then
    echo "Changin UID and GID and Fixing file permission..."
    groupmod -g $OGID odoo
    usermod -u $OUID -g $OGID odoo
    chown -R odoo:odoo /opt/odoo /usr/local
else
    if ! [[ "$OUID" == 2000 && "$OGID" == 2000 ]]; then
        echo "ERROR: OUID and OGID must be 2000 to skip changing the file permissions" 2>&1
        exit 1
    fi
fi
