#!/usr/bin/env bash

exec s6-setuidgid odoo bash -c "

if [ ! -z \"$PIP_INSTALL\" ]; then
    pip install ${PIP_INSTALL//,/ }
fi

if [ ! -z \"$PIP_INSTALL_FILE\" ]; then
    requirements-install ${PIP_INSTALL_FILE//,/ }
fi
"