#!/usr/bin/env bash

if [ "$(ls -A /opt/odoo/data)" ]; then
    echo "Data directory is not empty, not changing permissions"
else
    echo "Data directory is empty, changing permissions"
    chown -R odoo:odoo /opt/odoo/data
fi

if [ "$(ls -A /opt/odoo/logs)" ]; then
    echo "Logs directory is not empty, not changing permissions"
else
    echo "Logs directory is empty, changing permissions"
    chown -R odoo:odoo /opt/odoo/logs
fi