version: '2'

services:
  postgresql:
    image: postgres:14 # Please use bitnami/postgresql for production
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgres/data
    ports:
      - 5432:5432
    restart: unless-stopped

networks:
  default:
    external: true
    name: path-to-current-working-directory # Generate with `odooctl network-name`