#!/usr/bin/env bash

cd /opt/odoo || exit 1

if [ ! -z "$ODOO_DRY_RUN" ]; then
    secs=0
    while true; do
        sleep 300
        secs=$((secs+300))
        echo "Dry run: $secs seconds have passed" >&2
    done
fi

if [ ! -z "$(find /opt/odoo/pre-start.d -mindepth 1 -maxdepth 1 -type f -print -quit)" ]; then
    for f in /opt/odoo/pre-start.d/*; do
        echo "Running pre-start hook: $f"
        runuser -u odoo -- "$f"
    done
fi

# Workaround of https://github.com/just-containers/s6-overlay/issues/374
export HOME=/opt/odoo

exec s6-setuidgid odoo python server/odoo-bin ${OARGS}