name: Build Odoo 16

on:
  push:
    branches: 
        - master
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build-16:
    env:
      ODOO_VERSION: "16.0"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v3

      - name: Checkout Odoo
        uses: actions/checkout@v3
        with:
          repository: odoo/odoo
          path: odoo
          ref: "${{ env.ODOO_VERSION }}"

      - name: Checkout Odoo enterprise
        uses: actions/checkout@v3
        with:
          repository: odoo/enterprise
          path: enterprise
          ssh-key: ${{ secrets.ODOO_ENTERPRISE_SSH_KEY }}
          ref: "${{ env.ODOO_VERSION }}"

      - name: Get Odoo enterprise hash
        id: odoo-enterprise-hash
        run: |
          echo "hash=$(git -C enterprise rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Append Dockerfile
        run: |
          echo >> Dockerfile
          echo "LABEL com.mplus-software.branch=${{ env.ODOO_VERSION }}" >> Dockerfile
          echo "LABEL com.mplus-software.enterprise.revision=${{ steps.odoo-enterprise-hash.outputs.hash }}" >> Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build Odoo ${{ env.ODOO_VERSION }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            quay.io/mplus-software/odoo:latest
            quay.io/mplus-software/odoo:${{ env.ODOO_VERSION }}